version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./.docker_volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DummyPass123!
      POSTGRES_DB: sensor_insights_db
