# Generated by Django 5.2 on 2025-05-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                (
                    'temperature',
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    'humidity',
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    'air_quality',
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
            ],
        ),
    ]
